### ISSUE TITLE
部署智能合约 对交易签名进行ACL签名后 发送交易失败

### ISSUE THREAD

**Issue by yl123-y** [xuperchain/xuperchain#1048]
**Brief of the issue**
Describe here
./xchain-cli multisig send --tx ./tx.out ./key1.sign,./key2.sign ./key1.sign,./key2.sign
Failed to post tx:TX_SIGN_ERROR, logid:1621328512840973607_1_8081

**Your environment**
XuperChain and OS/Go/gcc version etc.
xchain-cli version master-b2d6bd2 2021-05-17-20:31:21
go version go1.12.5 linux/amd64
gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
**Repo steps**
Describe how to reproduce this issue.
Contract deployments send transactions

**Expected behaviours**
Describe what you expected to happen.
Return correct result
Tx id: 687e8e6ec357b99f8847019ac0f03f4d9eab9ee3608c13a0035ee5794d3c03af

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.
Failed to post tx:TX_SIGN_ERROR, logid:1621328512840973607_1_8081
**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by godeamon** [comment]
@yl123-y 
Please check the keys parameter of the signing command and the ACL of the contract account. The signed address needs to meet the ACL requirements before the transaction can be sent, otherwise the transaction will fail.
If the contract account ACL requires two address signatures, then the signature command needs to be executed twice, each time using the respective private key to sign.
